#!/bin/bash

#======================================================================#
#	 __     ___  __      __   __   __   ___  __
#	|__) | |__  |__)    /  ` /  \ |  \ |__  |__)
#	|    | |___ |  \    \__, \__/ |__/ |___ |  \
#
#	dmenu launcher
#======================================================================#


# Colors
color1="#d79921"
color2="#282828"

# Style
lines="50"
font="FontAwesome-13"


dmenu_run -nf $color1 -nb $color2 -sb $color1 -sf $color2 -fn 'FontAwesome-12' -p 'Type to search ▶'
